### ISSUE TITLE
Add ExactSequence

### ISSUE THREAD

**Issue by Shmaltalk** [F-Secure/pytest-voluptuous#5]
When checking exact values exist in a dictionary containing a list, rather than types, currently you need to import ExactSequence from voluptuous. Can it be added as a function in pytest_voluptuous as well?

**Comment by mtvx** [comment]
Is there harm in importing it directly from voluputous? We shouldn't duplicate code between the projects.

> Can it be added as a function in pytest_voluptuous as well?

I'm not sure what you mean by this - what sort of a function (`ExactSequence` is a class anyway, not function)?

(Sorry for not noticing your message earlier - I just didn't get email notification, no idea why.)

**Comment by Shmaltalk** [comment]
Hm I see what you're saying. I'm just finding it a bit confusing that I sometimes need to import only ExactSequence from voluptuous when everything else I'm using in a test file is from pytest voluptuous. 

Re: function, I mistyped.

**Comment by mtvx** [comment]
> I sometimes need to import only ExactSequence from voluptuous when everything else I'm using in a test file is from pytest voluptuous.

Don't worry, you import stuff from where you need, it's life as usual. Besides, your IDE will help you do that - you don't need to care too much about where it comes from.
